/* Shared online layer for the HvH sandboxes: 1v1 over WebRTC (PeerJS). No game server needed.
   Host creates a room code, friend joins with it (or via the ?join=CODE link). */
(function(){
const q=new URLSearchParams(location.search);
const cfg={debug:0,config:{iceServers:[{urls:'stun:stun.l.google.com:19302'},{urls:'stun:stun1.l.google.com:19302'},{urls:'stun:global.stun.twilio.com:3478'}]}};
/* Optional: use your own TURN relay for strict networks, e.g. add {urls:'turn:your.server:3478',username:'u',credential:'p'} to iceServers above. */
if(q.get('peerhost'))Object.assign(cfg,{host:q.get('peerhost'),port:+q.get('peerport')||9000,path:q.get('peerpath')||'/',secure:q.get('secure')=='1'});
const H={};let ui,statusEl,codeEl,btn;
const Net={open:false,host:false,code:'',ping:0,peer:null,conn:null,
 on(f){H.m=f},onOpen(f){H.o=f},onClose(f){H.c=f},
 send(o){if(this.conn&&this.conn.open){try{this.conn.send(o)}catch(e){}}},
 status(t,err){if(statusEl){statusEl.textContent=t;statusEl.style.color=err?'#ff6b6b':'#9aa0a6'}},
 hostGame(){this.reset();this.host=true;const al='ABCDEFGHJKMNPQRSTUVWXYZ23456789';let c='';for(let i=0;i<5;i++)c+=al[Math.floor(Math.random()*al.length)];this.code=c;
  const p=this.peer=new Peer('hvhx-'+c,cfg);p.on('open',()=>{codeEl.textContent=c;codeEl.parentNode.style.display='block';const link=location.origin+location.pathname+'?join='+c;$('hvh-link').value=link;this.status('Room ready. Send your friend the code or the link and wait...')});
  p.on('connection',cn=>{if(this.conn&&this.conn.open){cn.close();return}this.setup(cn)});p.on('error',e=>this.status('Network error: '+(e.type||e),1))},
 joinGame(code){this.reset();this.host=false;code=(code||'').trim().toUpperCase();if(!code){this.status('Enter a room code',1);return}this.status('Connecting to room '+code+'...');
  const p=this.peer=new Peer(undefined,cfg);p.on('open',()=>{const cn=p.connect('hvhx-'+code,{reliable:true});this.setup(cn);setTimeout(()=>{if(!this.open)this.status('Could not reach that room. Check the code, or ask the host to re-host.',1)},12000)});p.on('error',e=>this.status(e.type=='peer-unavailable'?'No room with that code. Check the code and make sure the host is waiting.':'Network error: '+(e.type||e),1))},
 setup(cn){this.conn=cn;cn.on('open',()=>{this.open=true;this.status('Connected!');ui.style.display='none';btn.textContent='ONLINE: CONNECTED';btn.style.borderColor='#8fe03a';H.o&&H.o();clearInterval(this._pi);this._pi=setInterval(()=>this.send({t:'ping',ts:Date.now()}),2000)});
  cn.on('data',d=>{if(!d)return;if(d.t=='ping')cn.send({t:'pong',ts:d.ts});else if(d.t=='pong')this.ping=Date.now()-d.ts;else H.m&&H.m(d)});
  cn.on('close',()=>{if(this.open){this.open=false;btn.textContent='ONLINE 1v1';btn.style.borderColor='';H.c&&H.c()}this.status('Disconnected',1)});cn.on('error',e=>this.status('Connection error: '+(e.type||e),1))},
 reset(){try{this.conn&&this.conn.close()}catch(e){}try{this.peer&&this.peer.destroy()}catch(e){}this.open=false;this.conn=null;clearInterval(this._pi);if(codeEl)codeEl.parentNode.style.display='none'},
 lobby(){if(document.pointerLockElement)document.exitPointerLock();ui.style.display='flex'}};
const $=id=>document.getElementById(id);
function build(){const st=document.createElement('style');st.textContent='#hvh-btn{position:fixed;left:10px;top:10px;z-index:99998;background:#16181c;color:#e8e8ea;border:1px solid #3f84e8;padding:7px 12px;font:bold 11px Tahoma,Verdana,sans-serif;letter-spacing:.1em;cursor:pointer}#hvh-btn:hover{background:#243a60}#hvh-ui{position:fixed;inset:0;z-index:99999;background:rgba(6,7,9,.86);display:none;align-items:center;justify-content:center;font:12px Tahoma,Verdana,sans-serif;color:#e8e8ea}#hvh-box{width:440px;max-width:94vw;background:linear-gradient(#121316,#0d0e10);border:1px solid #000;box-shadow:0 0 0 1px #34363a;padding:20px}#hvh-box h2{margin:0 0 4px;font-size:15px;letter-spacing:.18em}#hvh-box .bar{height:2px;background:linear-gradient(90deg,#9fca2b,#34c4e5,#a057e8,#ff8a3d);margin:-20px -20px 16px}#hvh-box p{color:#8b8f98;margin:0 0 14px;line-height:1.5}#hvh-box button,#hvh-box input{font:bold 12px Tahoma,Verdana,sans-serif;background:#1b1c1f;color:#e8e8ea;border:1px solid #000;box-shadow:0 0 0 1px #34363a inset;padding:9px 12px}#hvh-box button{cursor:pointer}#hvh-box button:hover{background:#243a60}#hvh-box .row{display:flex;gap:8px;margin-bottom:12px}#hvh-box input{flex:1;text-transform:uppercase;letter-spacing:.2em;text-align:center}#hvh-code{font-size:34px;letter-spacing:.3em;text-align:center;color:#3f84e8;margin:6px 0 10px}#hvh-box small{display:block;margin-top:6px;color:#8b8f98}';document.head.appendChild(st);
 btn=document.createElement('button');btn.id='hvh-btn';btn.textContent='ONLINE 1v1';btn.onclick=()=>Net.lobby();document.body.appendChild(btn);
 ui=document.createElement('div');ui.id='hvh-ui';ui.innerHTML='<div id="hvh-box"><div class="bar"></div><h2>ONLINE 1v1</h2><p>Play a friend directly (peer-to-peer, no server needed). One of you hosts, the other joins with the code.</p><div class="row"><button id="hvh-host" style="flex:1">HOST A MATCH</button></div><div id="hvh-roombox" style="display:none"><div id="hvh-code"></div><div class="row"><input id="hvh-link" readonly><button id="hvh-copy">COPY LINK</button></div></div><div class="row"><input id="hvh-in" maxlength="5" placeholder="ROOM CODE"><button id="hvh-join">JOIN</button></div><div id="hvh-st" style="min-height:16px;color:#9aa0a6"></div><div class="row" style="margin:14px 0 0"><button id="hvh-x" style="flex:1">CLOSE</button></div></div>';document.body.appendChild(ui);
 statusEl=$('hvh-st');codeEl=$('hvh-code');$('hvh-host').onclick=()=>Net.hostGame();$('hvh-join').onclick=()=>Net.joinGame($('hvh-in').value);$('hvh-x').onclick=()=>{ui.style.display='none'};$('hvh-copy').onclick=()=>{const l=$('hvh-link');l.select();try{navigator.clipboard.writeText(l.value)}catch(e){document.execCommand('copy')}Net.status('Link copied')};
 $('hvh-in').addEventListener('keydown',e=>{e.stopPropagation();if(e.key=='Enter')Net.joinGame($('hvh-in').value)});$('hvh-in').addEventListener('keyup',e=>e.stopPropagation());
 const j=q.get('join');if(j){ui.style.display='flex';$('hvh-in').value=j;setTimeout(()=>Net.joinGame(j),300)}}
window.Net=Net;if(document.body)build();else addEventListener('DOMContentLoaded',build)})();
